### ISSUE TITLE
activate components i SH-Tool

### ISSUE THREAD

**Issue by Simonk007** [ulriklystbaek/smarthouse-ha#1]
Hi,
Im kinda new into the Smarthouse world.
Could you show me using screenshots how to activate components in SH-tool.

**Comment by ulriklystbaek** [comment]
![2023-12-02 13_09_00-SHTOOL Controller configurator _  Fil ikke gemt   - 7 9 37](https://github.com/ulriklystbaek/smarthouse-ha/assets/6458305/eb178098-177b-42f4-a918-6cb85642cde9)
